Added check of "make install" ability.
This closes #136 issue on GitHub.

diff --git a/auto/make b/auto/make
--- a/auto/make
+++ b/auto/make
@@ -204,11 +204,20 @@ done
 
 cat << END >> $NXT_MAKEFILE
 
-.PHONY: install ${NXT_DAEMON}-install
+.PHONY: install ${NXT_DAEMON}-install install-check
 
 install: ${NXT_DAEMON}-install
 
-${NXT_DAEMON}-install: $NXT_DAEMON
+install-check:
+	@test -n "\$(DESTDIR)$NXT_PREFIX" \\
+	|| (echo; \\
+	    echo "error: to make install you need either"; \\
+	    echo "    to configure --prefix option"; \\
+	    echo "    or to set DESTDIR environment variable."; \\
+	    echo; \\
+	    exit 1)
+
+${NXT_DAEMON}-install: $NXT_DAEMON install-check
 	install -d \$(DESTDIR)$NXT_SBINDIR
 	install -p $NXT_BUILD_DIR/$NXT_DAEMON \$(DESTDIR)$NXT_SBINDIR/
 	install -d \$(DESTDIR)$NXT_STATE
